import { NPCProfile } from '../../../../types';

/**
 * 恸哭者 (Lamenters) - 厄运折磨
 */
export const LAMENTERS_BESTIARY: Record<string, Partial<NPCProfile>> = {
  'lamenters_neophyte': {
    name: '恸哭者新兵', status: '受誓学徒', attributes: { weaponSkill: 45, ballisticSkill: 40, strength: 55, toughness: 60, agility: 45, intelligence: 35, perception: 45, willpower: 65, fellowship: 20 }, trait: '厄运折磨, 星海本能, 体型·普通', skill: '普通知识·国教, 闪避, 潜行, 医疗', equipment: '侦察兵复合板甲, 精工阿斯塔特爆弹手枪, 阿斯塔特格斗刀', tags: ['帝国', '阿斯塔特', '新兵', '恸哭者'], hp: 12, maxHp: 12, ahp: 60, movement: 4, baseMeleeDamage: '2 (S/20)', weaponStats: '精工阿斯塔特爆弹手枪, 阿斯塔特格斗刀'
  }, 'lamenters_tactical_marine': {
    name: '恸哭者战术修士', status: '战团基石', attributes: { weaponSkill: 55, ballisticSkill: 55, strength: 75, toughness: 70, agility: 60, intelligence: 35, perception: 45, willpower: 80, fellowship: 10 }, trait: '死亡天使, 厄运折磨, 星海本能, 体型·大型', skill: '普通知识·技术, 闪避, 战术', equipment: 'MK VII 型动力甲, 阿斯塔特爆弹枪, 阿斯塔特格斗刀', tags: ['帝国', '阿斯塔特', '恸哭者'], hp: 14, maxHp: 14, ahp: 70, movement: 7, baseMeleeDamage: '3 (S/20)', weaponStats: '阿斯塔特爆弹枪, 阿斯塔特格斗刀'
  }, 'lamenters_intercessor': {
    name: '恸哭者仲裁者', status: '原铸之血', attributes: { weaponSkill: 75, ballisticSkill: 65, strength: 80, toughness: 85, agility: 80, intelligence: 40, perception: 50, willpower: 100, fellowship: 15 }, trait: '原铸改造, 厄运折磨, 死亡天使, 百战幸存, 星海本能, 体型·大型', skill: '战术, 闪避, 警觉', equipment: 'Mk X 战术型动力甲, 爆弹步枪, 精工阿斯塔特爆弹手枪', tags: ['帝国', '阿斯塔特', '原铸', '恸哭者'], hp: 17, maxHp: 17, ahp: 85, movement: 9, baseMeleeDamage: '4 (S/20)', weaponStats: '爆弹步枪, 精工阿斯塔特爆弹手枪'
  }, 'lamenters_sanguinary_priest': {
    name: '恸哭者圣血牧师', status: '圣血守护', attributes: { weaponSkill: 65, ballisticSkill: 55, strength: 80, toughness: 70, agility: 75, intelligence: 80, perception: 55, willpower: 95, fellowship: 35 }, trait: '死亡天使, 厄运折磨, 星海本能, 百战幸存, 英雄之躯, 体型·大型', skill: '医疗, 普通知识·技术, 战术, 逻辑', equipment: '精工MK VII 型动力甲, 阿斯塔特圣杯, 护道器, 阿斯塔特格斗刀', tags: ['帝国', '阿斯塔特', '药剂师', '圣血牧师', '恸哭者'], hp: 14, maxHp: 14, ahp: 70, movement: 8, baseMeleeDamage: '4 (S/20)', weaponStats: '阿斯塔特格斗刀'
  }, 'lamenters_vanguard_veteran': {
    name: '恸哭者先锋老兵', status: '血色先锋', attributes: { weaponSkill: 85, ballisticSkill: 55, strength: 90, toughness: 70, agility: 80, intelligence: 40, perception: 55, willpower: 95, fellowship: 20 }, trait: '死亡天使, 厄运折磨, 星海本能, 百战幸存, 先锋追猎, 体型·大型', skill: '指挥, 战术, 闪避, 特技', equipment: '精工MK VII 型动力甲, 双联闪电爪, 阿斯塔特喷气背包', tags: ['帝国', '阿斯塔特', '老兵', '跳帮', '恸哭者'], hp: 14, maxHp: 14, ahp: 70, movement: 9, baseMeleeDamage: '4 (S/20)', weaponStats: '双联闪电爪'
  }, 'lamenters_ancient': {
    name: '恸哭者旗手', status: '战旗守护者', attributes: { weaponSkill: 75, ballisticSkill: 60, strength: 80, toughness: 75, agility: 70, intelligence: 45, perception: 55, willpower: 105, fellowship: 40 }, trait: '死亡天使, 厄运折磨, 星海本能, 百战幸存, 英雄领袖, 体型·大型', skill: '指挥, 战术, 魅力', equipment: 'MK VII 型动力甲, 恸哭者战旗, 阿斯塔特爆弹枪', tags: ['帝国', '阿斯塔特', '旗手', '恸哭者'], hp: 15, maxHp: 15, ahp: 75, movement: 8, baseMeleeDamage: '4 (S/20)', weaponStats: '阿斯塔特爆弹枪'
  }, 'lamenters_malakim_phoros': {
    name: '马拉金·弗罗斯', status: '恸哭者战团长', attributes: { weaponSkill: 95, ballisticSkill: 80, strength: 95, toughness: 85, agility: 85, intelligence: 60, perception: 70, willpower: 115, fellowship: 70 }, trait: '死亡天使, 厄运折磨, 星海本能, 百战幸存, 执政官权威, 英雄之躯, 体型·大型', skill: '指挥, 战术, 魅力, 普通知识·阿斯塔特修会', equipment: '圣物MK VII 型动力甲, 忏悔圣言, 精工阿斯塔特爆弹手枪', tags: ['帝国', '阿斯塔特', '英雄', '战团长', '恸哭者'], hp: 17, maxHp: 17, ahp: 85, movement: 9, baseMeleeDamage: '4 (S/20)', weaponStats: '忏悔圣言, 精工阿斯塔特爆弹手枪'
  }, 'lamenters_scout': {
    name: '恸哭者侦察兵', status: '新兵 (恸哭者)', attributes: { weaponSkill: 45, ballisticSkill: 45, strength: 45, toughness: 40, agility: 55, intelligence: 30, perception: 55, willpower: 35, fellowship: 25 }, trait: '星海本能, 厄运折磨, 体型·普通', skill: '潜行, 追迹, 调查', equipment: '侦察兵复合板甲, 狙击爆弹枪, 阿斯塔特格斗刀', tags: ['帝国', '阿斯塔特', '侦察兵', '恸哭者'], hp: 8, maxHp: 8, ahp: 40, movement: 5, baseMeleeDamage: '2 (S/20)', weaponStats: '狙击爆弹枪, 阿斯塔特格斗刀'
  }, 'lamenters_primaris_scout': {
    name: '恸哭者侦察快遣兵 (原铸)', status: '移动阴影 (恸哭者)', attributes: { weaponSkill: 50, ballisticSkill: 55, strength: 55, toughness: 50, agility: 60, intelligence: 40, perception: 65, willpower: 45, fellowship: 30 }, trait: '原铸改造, 厄运折磨, 体型·普通', skill: '潜行, 调查, 特技', equipment: 'Mk X 福波斯型动力甲, 消音爆弹枪, 阿斯塔特格斗刀', tags: ['帝国', '阿斯塔特', '原铸', '侦察', '恸哭者'], hp: 10, maxHp: 10, ahp: 50, movement: 6, baseMeleeDamage: '2 (S/20)', weaponStats: '消音爆弹枪, 阿斯塔特格斗刀'
  }, 'lamenters_sergeant': {
    name: '恸哭者士官', status: '小队战识 (恸哭者)', attributes: { weaponSkill: 73, ballisticSkill: 65, strength: 75, toughness: 60, agility: 75, intelligence: 45, perception: 50, willpower: 65, fellowship: 45 }, trait: '死亡天使, 厄运折磨, 战术核心, 百战幸存, 体型·大型', skill: '指挥, 战术, 警觉', equipment: '精工MK VII 型动力甲, 动力拳套, 精工阿斯塔特爆弹手枪, 鸟卜仪', tags: ['帝国', '阿斯塔特', '士官', '恸哭者'], hp: 12, maxHp: 12, ahp: 60, movement: 8, baseMeleeDamage: '3 (S/20)', weaponStats: '动力拳套, 精工阿斯塔特爆弹手枪'
  }, 'lamenters_veteran': {
    name: '恸哭者先锐老兵', status: '虚空先锋 (恸哭者)', attributes: { weaponSkill: 75, ballisticSkill: 70, strength: 80, toughness: 65, agility: 60, intelligence: 40, perception: 60, willpower: 75, fellowship: 25 }, trait: '死亡天使, 厄运折磨, 虚空先锋, 百战幸存, 体型·大型', skill: '特技, 闪避, 潜行', equipment: 'Mk X 福波斯型动力甲, 瑞扎型动力剑, 消音爆弹枪', tags: ['帝国', '阿斯塔特', '老兵', '恸哭者'], hp: 13, maxHp: 13, ahp: 65, movement: 7, baseMeleeDamage: '4 (S/20)', weaponStats: '消音爆弹枪, 瑞扎型动力剑'
  }, 'lamenters_primaris_infiltrator': {
    name: '恸哭者渗透者', status: '暗影原铸 (恸哭者)', attributes: { weaponSkill: 50, ballisticSkill: 55, strength: 60, toughness: 50, agility: 55, intelligence: 45, perception: 60, willpower: 45, fellowship: 30 }, trait: '原铸改造, 厄运折磨, 暗影渗透, 星海本能, 死亡天使, 体型·大型', skill: '潜行, 调查, 警觉', equipment: 'Mk X 福波斯型动力甲, 消音爆弹枪, 阿斯塔特格斗刀', tags: ['帝国', '阿斯塔特', '原铸', '恸哭者'], hp: 10, maxHp: 10, ahp: 50, movement: 6, baseMeleeDamage: '3 (S/20)', weaponStats: '消音爆弹枪, 阿斯塔特格斗刀'
  }, 'lamenters_primaris_intercessor': {
    name: '恸哭者仲裁者 (标准原铸)', status: '钢铁防线 (恸哭者)', attributes: { weaponSkill: 55, ballisticSkill: 60, strength: 70, toughness: 55, agility: 55, intelligence: 40, perception: 50, willpower: 50, fellowship: 30 }, trait: '原铸改造, 厄运折磨, 百战幸存, 体型·大型', skill: '身体素质, 战术, 闪避', equipment: 'Mk X 战术型动力甲, 爆弹步枪, 精工阿斯塔特爆弹手枪, 破片手雷（精英版）', tags: ['帝国', '阿斯塔特', '原铸', '标准', '恸哭者'], hp: 11, maxHp: 11, ahp: 55, movement: 6, baseMeleeDamage: '3 (S/20)', weaponStats: '爆弹步枪, 精工阿斯塔特爆弹手枪, 破片手雷（精英版）'
  }, 'lamenters_primaris_hellblaster': {
    name: '恸哭者地狱火战士', status: '毁灭之光 (恸哭者)', attributes: { weaponSkill: 60, ballisticSkill: 75, strength: 75, toughness: 60, agility: 50, intelligence: 45, perception: 70, willpower: 65, fellowship: 30 }, trait: '原铸改造, 厄运折磨, 死亡天使, 工业直觉, 百战幸存, 体型·大型', skill: '战术, 警觉', equipment: 'Mk X 战术型动力甲, 阿斯塔特爆弹枪, 精工阿斯塔特爆弹手枪', tags: ['帝国', '阿斯塔特', '原铸', '重装火力', '恸哭者'], hp: 12, maxHp: 12, ahp: 60, movement: 6, baseMeleeDamage: '3 (S/20)', weaponStats: '阿斯塔特爆弹枪, 精工阿斯塔特爆弹手枪'
  }, 'lamenters_primaris_aggressor': {
    name: '恸哭者重装火兵', status: '重装毁灭 (恸哭者)', attributes: { weaponSkill: 65, ballisticSkill: 60, strength: 85, toughness: 70, agility: 45, intelligence: 45, perception: 45, willpower: 65, fellowship: 20 }, trait: '原铸改造, 厄运折磨, 连射压制, 死亡天使, 百战幸存, 体型·大型', skill: '恐吓, 战术, 警觉', equipment: 'Mk X 格拉维斯型动力甲, 动力拳套, 阿斯塔特爆弹枪', tags: ['帝国', '阿斯塔特', '原铸', '重装', '恸哭者'], hp: 14, maxHp: 14, ahp: 70, movement: 5, baseMeleeDamage: '4 (S/20)', weaponStats: '动力拳套, 阿斯塔特爆弹枪'
  }, 'lamenters_destroyer': {
    name: '恸哭者毁灭者', status: '虚空毁灭 (恸哭者)', attributes: { weaponSkill: 75, ballisticSkill: 70, strength: 105, toughness: 70, agility: 40, intelligence: 45, perception: 50, willpower: 80, fellowship: 30 }, trait: '死亡天使, 厄运折磨, 终结者意志, 百战幸存, 体型·大型', skill: '战术, 警觉, 恐吓', equipment: '不屈型战术无畏装甲, 雷霆锤, 重型爆弹枪', tags: ['帝国', '阿斯塔特', '精英', '终结者', '恸哭者'], hp: 14, maxHp: 14, ahp: 70, movement: 5, baseMeleeDamage: '5 (S/20)', weaponStats: '雷霆锤, 重型爆弹枪'
  }, 'lamenters_terminator': {
    name: '恸哭者老兵终结者', status: '虚空毁灭者 (恸哭者)', attributes: { weaponSkill: 80, ballisticSkill: 70, strength: 100, toughness: 65, agility: 40, intelligence: 50, perception: 55, willpower: 80, fellowship: 35 }, trait: '死亡天使, 厄运折磨, 终结者意志, 百战幸存, 体型·大型', skill: '战术, 警觉, 恐吓', equipment: '精工不屈型战术无畏装甲, 动力拳套, 双联重型爆弹枪', tags: ['帝国', '阿斯塔特', '精英', '终结者', '老兵', '恸哭者'], hp: 13, maxHp: 13, ahp: 65, movement: 5, baseMeleeDamage: '5 (S/20)', weaponStats: '动力拳套, 双联重型爆弹枪'
  }, 'lamenters_destroyer_veteran': {
    name: '恸哭者毁灭者老兵', status: '重型清洗者 (恸哭者)', attributes: { weaponSkill: 85, ballisticSkill: 80, strength: 130, toughness: 85, agility: 30, intelligence: 55, perception: 65, willpower: 90, fellowship: 40 }, trait: '钢铁长城, 厄运折磨, 终结者意志, 百战幸存, 体型·大型', skill: '指挥, 战术, 侦察', equipment: '不屈型战术无畏装甲, 百夫长装甲, 机甲型突击炮, 双联重型爆弹枪', tags: ['帝国', '阿斯塔特', '老兵', '精英', '毁灭者', '恸哭者'], hp: 17, maxHp: 17, ahp: 85, movement: 4, baseMeleeDamage: '6 (S/20)', weaponStats: '机甲型突击炮, 双联重型爆弹枪'
  }, 'lamenters_centurion': {
    name: '恸哭者百夫长', status: '移动堡垒 (恸哭者)', attributes: { weaponSkill: 85, ballisticSkill: 80, strength: 130, toughness: 85, agility: 30, intelligence: 55, perception: 65, willpower: 90, fellowship: 40 }, trait: '钢铁长城, 厄运折磨, 终结者意志, 百战幸存, 体型·大型', skill: '指挥, 战术, 警觉', equipment: '不屈型战术无畏装甲, 百夫长装甲, 机甲型突击炮, 双联重型爆弹枪', tags: ['帝国', '阿斯塔特', '老兵', '精英', '百夫长', '恸哭者'], hp: 17, maxHp: 17, ahp: 85, movement: 4, baseMeleeDamage: '6 (S/20)', weaponStats: '机甲型突击炮, 双联重型爆弹枪'
  }, 'lamenters_apothecary': {
    name: '恸哭者药剂师', status: '基因守护者 (恸哭者)', attributes: { weaponSkill: 55, ballisticSkill: 55, strength: 70, toughness: 55, agility: 60, intelligence: 80, perception: 55, willpower: 50, fellowship: 35 }, trait: '守护职责, 厄运折磨, 战地急救, 星海本能, 死亡天使, 体型·大型', skill: '医疗, 逻辑, 调查', equipment: '护道器, 还原者, 阿斯塔特爆弹枪, MK VII 型动力甲', tags: ['帝国', '阿斯塔特', '药剂师', '恸哭者'], hp: 11, maxHp: 11, ahp: 55, movement: 7, baseMeleeDamage: '3 (S/20)', weaponStats: '阿斯塔特爆弹枪(S:45 D:8 容量:30 连发:可)'
  }, 'lamenters_techmarine': {
    name: '恸哭者技术军士', status: '机械先行者 (恸哭者)', attributes: { weaponSkill: 55, ballisticSkill: 55, strength: 80, toughness: 65, agility: 45, intelligence: 85, perception: 60, willpower: 55, fellowship: 20 }, trait: '机械修复, 厄运折磨, 多功能操作, 工业直觉, 死亡天使, 体型·大型', skill: '评估, 逻辑, 调查, 普通知识·技术', equipment: '伺服臂组, 阿斯塔特链锯斧, 精工阿斯塔特爆弹手枪, MK VII 型动力甲', tags: ['帝国', '阿斯塔特', '技术支持', '恸哭者'], hp: 13, maxHp: 13, ahp: 65, movement: 5, baseMeleeDamage: '4 (S/20)', weaponStats: '伺服臂组, 阿斯塔特链锯斧, 精工阿斯塔特爆弹手枪'
  }, 'lamenters_librarian': {
    name: '恸哭者智库', status: '虚空灵能者 (恸哭者)', attributes: { weaponSkill: 50, ballisticSkill: 50, strength: 65, toughness: 55, agility: 55, intelligence: 70, perception: 60, willpower: 90, fellowship: 35 }, trait: '厄运折磨, 虚空扭曲, 星海本能, 死亡天使, 体型·大型', skill: '祈求, 逻辑, 调查, 灵能掌控, 能量通道', equipment: '灵能剑, 灵能兜帽, 阿斯塔特爆弹枪, MK VII 型动力甲', tags: ['帝国', '阿斯塔特', '灵能者', '恸哭者'], hp: 11, maxHp: 11, ahp: 55, movement: 6, baseMeleeDamage: '3 (S/20)', weaponStats: '灵能剑, 阿斯塔特爆弹枪'
  }, 'lamenters_chaplain': {
    name: '恸哭者牧师', status: '执政官意志 (恸哭者)', attributes: { weaponSkill: 65, ballisticSkill: 50, strength: 75, toughness: 60, agility: 55, intelligence: 50, perception: 45, willpower: 95, fellowship: 60 }, trait: '狂怒祷言, 厄运折磨, 不屈核心, 星海本能, 死亡天使, 体型·大型', skill: '指挥, 恐吓, 魅力', equipment: '精工MK VII 型动力甲, 克洛休斯权杖, 罗兹利乌斯护盾, 精工阿斯塔特爆弹手枪', tags: ['帝国', '阿斯塔特', '牧师', '恸哭者'], hp: 12, maxHp: 12, ahp: 60, movement: 6, baseMeleeDamage: '3 (S/20)', weaponStats: '克洛休斯权杖, 精工阿斯塔特爆弹手枪'
  }, 'lamenters_captain': {
    name: '恸哭者连长', status: '虚空领主 (恸哭者)', attributes: { weaponSkill: 85, ballisticSkill: 80, strength: 85, toughness: 75, agility: 90, intelligence: 65, perception: 70, willpower: 85, fellowship: 70 }, trait: '执政官权威, 厄运折磨, 英雄之躯, 星海本能, 死亡天使, 百战幸存, 体型·大型', skill: '指挥, 魅力, 战术', equipment: '圣物MK VII 型动力甲, 泰拉型动力剑, 精工Mk II“日怒”型等离子手枪', tags: ['帝国', '阿斯塔特', '英雄', '恸哭者'], hp: 15, maxHp: 15, ahp: 75, movement: 10, baseMeleeDamage: '4 (S/20)', weaponStats: '精工Mk II“日怒”型等离子手枪, 泰拉型动力剑'
  }, 'lamenters_dreadnought': {
    name: '恸哭者古老无畏', status: '钢铁执政官 (恸哭者)', attributes: { weaponSkill: 55, ballisticSkill: 65, strength: 120, toughness: 110, agility: 35, intelligence: 50, perception: 50, willpower: 75, fellowship: 15 }, trait: '不朽生命, 厄运折磨, 星海本能, 死亡天使, 体型·巨大', skill: '战术, 恐吓, 警觉', equipment: '无畏机甲, 机甲型突击炮, 双联激光炮, 无畏型动力爪, 导弹巢', tags: ['帝国', '阿斯塔特', '无畏机甲', '恸哭者'], hp: 22, maxHp: 22, ahp: 110, movement: 5, baseMeleeDamage: '6 (S/20)', weaponStats: '机甲型突击炮, 双联激光炮, 无畏型动力爪'

  }
};
