import fs from 'fs';
import path from 'path';

const primarchs30k = {
  'lion_el_jonson_30k': {
    name: '莱昂·艾尔庄森 (Lion El\'Jonson) - 30K',
    status: '暗黑天使原体 / 第一军团之主',
    attributes: { weaponSkill: 100, ballisticSkill: 90, strength: 75, toughness: 75, agility: 85, intelligence: 95, perception: 95, willpower: 100, fellowship: 80 },
    trait: '【原体】：全属性受超凡加成；【战略大师】：指挥对抗时获得 +20 加成；【死亡天使之主】：麾下第一军团单位免疫恐惧；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '武器技能, 指挥, 战略, 逻辑, 警觉',
    equipment: '狮心剑, 狮子盔甲, 狼牙棒',
    tags: ['帝国', '阿斯塔特', '原体', '暗黑天使', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 9,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '狮心剑(S:+45 D:22 能量 锋利)'
  },
  'fulgrim_30k': {
    name: '福格瑞姆 (Fulgrim) - 30K',
    status: '帝皇之子原体 / 完美追求者',
    attributes: { weaponSkill: 100, ballisticSkill: 90, strength: 70, toughness: 70, agility: 95, intelligence: 90, perception: 100, willpower: 85, fellowship: 100 },
    trait: '【原体】：全属性受超凡加成；【完美追求】：武器技能对抗失败时可重试一次；【高贵仪态】：社交对抗获得 +20 加成；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '武器技能, 艺术, 社交, 警觉, 突击',
    equipment: '劳恩之剑, 完美之铠',
    tags: ['帝国', '阿斯塔特', '原体', '帝皇之子', '30K', '英雄'],
    hp: 14,
    maxHp: 14,
    ahp: 100,
    movement: 10,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '劳恩之剑(S:+40 D:20 能量 毒素 锋利)'
  },
  'perturabo_30k': {
    name: '佩图拉博 (Perturabo) - 30K',
    status: '钢铁勇士原体 / 围攻大师',
    attributes: { weaponSkill: 90, ballisticSkill: 100, strength: 85, toughness: 85, agility: 65, intelligence: 100, perception: 95, willpower: 95, fellowship: 60 },
    trait: '【原体】：全属性受超凡加成；【围攻大师】：对防御工事伤害翻倍；【冷酷逻辑】：无视所有心理压力的负面影响；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '建筑, 逻辑, 射击技能, 指挥, 数学',
    equipment: '碎裂者, 标志之甲',
    tags: ['帝国', '阿斯塔特', '原体', '钢铁勇士', '30K', '英雄'],
    hp: 17,
    maxHp: 17,
    ahp: 130,
    movement: 7,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '标志之甲(内置双联爆弹枪 S:+10 D:15), 碎裂者(S:+55 D:28 冲击)'
  },
  'jaghatai_khan_30k': {
    name: '察合台可汗 (Jaghatai Khan) - 30K',
    status: '白色伤疤原体 / 大汗',
    attributes: { weaponSkill: 100, ballisticSkill: 85, strength: 75, toughness: 75, agility: 100, intelligence: 90, perception: 100, willpower: 95, fellowship: 85 },
    trait: '【原体】：全属性受超凡加成；【风之子】：移动力恒定 +5；【闪电突击】：冲锋时攻击次数翻倍；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '武器技能, 驾驶, 警觉, 突击, 诗歌',
    equipment: '白虎弯刀, 追风者盔甲',
    tags: ['帝国', '阿斯塔特', '原体', '白色伤疤', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 15,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '白虎弯刀(S:+45 D:20 能量 撕裂)'
  },
  'konrad_curze_30k': {
    name: '康拉德·科兹 (Konrad Curze) - 30K',
    status: '午夜领主原体 / 夜之主',
    attributes: { weaponSkill: 95, ballisticSkill: 85, strength: 75, toughness: 75, agility: 95, intelligence: 90, perception: 100, willpower: 80, fellowship: 50 },
    trait: '【原体】：全属性受超凡加成；【恐惧化身】：全场敌人承受意志(WP)-20对抗，否则由于恐惧属性减半；【阴影潜行】：处在黑暗中时无法被远程锁定；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '潜行, 刑讯, 武器技能, 警觉, 追踪',
    equipment: '慈悲与宽恕, 恶梦之甲',
    tags: ['帝国', '阿斯塔特', '原体', '午夜领主', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 10,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '慈悲与宽恕(S:+45 D:22 撕裂 能量)'
  },
  'ferrus_manus_30k': {
    name: '费鲁斯·马努斯 (Ferrus Manus) - 30K',
    status: '钢铁之手原体 / 戈尔贡',
    attributes: { weaponSkill: 95, ballisticSkill: 90, strength: 90, toughness: 90, agility: 65, intelligence: 100, perception: 90, willpower: 100, fellowship: 65 },
    trait: '【原体】：全属性受超凡加成；【金属之肤】：获得全物理抗性+15；【技术工匠】：能够瞬间解析并修复任何复杂机械；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '锻造, 武器技能, 逻辑, 强健, 警觉',
    equipment: '碎裂者 (Forgebreaker), 戈尔贡之铠',
    tags: ['帝国', '阿斯塔特', '原体', '钢铁之手', '30K', '英雄'],
    hp: 18,
    maxHp: 18,
    ahp: 150,
    movement: 7,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '碎裂者(S:+55 D:28 冲击)'
  },
  'angron_30k': {
    name: '安格隆 (Angron) - 30K',
    status: '吞世者原体 / 红天使',
    attributes: { weaponSkill: 100, ballisticSkill: 60, strength: 85, toughness: 85, agility: 90, intelligence: 70, perception: 95, willpower: 85, fellowship: 40 },
    trait: '【原体】：全属性受超凡加成；【屠夫钉刺】：进入战斗后每秒力量(S)与敏捷(Ag)增加，但不分敌我；【永恒愤怒】：免疫眩晕与精神控制；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '武器技能, 突击, 强健, 警觉, 威压',
    equipment: '血父, 血子',
    tags: ['帝国', '阿斯塔特', '原体', '吞世者', '30K', '英雄'],
    hp: 17,
    maxHp: 17,
    ahp: 120,
    movement: 10,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '血父/血子(S:+50 D:25 撕裂 残暴)'
  },
  'roboute_guilliman_30k': {
    name: '罗伯特·基里曼 (Roboute Guilliman) - 30K',
    status: '极限战士原体 / 奥特拉玛之主',
    attributes: { weaponSkill: 95, ballisticSkill: 95, strength: 75, toughness: 75, agility: 75, intelligence: 100, perception: 95, willpower: 100, fellowship: 95 },
    trait: '【原体】：全属性受超凡加成；【理论与实践】：战斗中可消耗一秒解析敌人弱点，并获得后续攻击+20加成；【帝国摄政】：其在场时资源消耗与补给效率增加；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '管理, 指挥, 武器技能, 射击技能, 逻辑',
    equipment: '統御之剑, 复仇之手',
    tags: ['帝国', '阿斯塔特', '原体', '极限战士', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 8,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '統御之剑(S:+45 D:22 能量 权威)'
  },
  'mortarion_30k': {
    name: '莫塔里安 (Mortarion) - 30K',
    status: '死亡守卫原体 / 苍白之主',
    attributes: { weaponSkill: 95, ballisticSkill: 90, strength: 80, toughness: 95, agility: 70, intelligence: 90, perception: 95, willpower: 100, fellowship: 50 },
    trait: '【原体】：全属性受超凡加成；【耐力巅峰】：免疫所有自然毒素与环境疾病，HP 额外+5；【剧毒迷雾】：5米范围内生物每秒承受 T 对抗，失败损失 1HP；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '强健, 武器技能, 生物学, 警觉, 耐受',
    equipment: '寂静, 提灯',
    tags: ['帝国', '阿斯塔特', '原体', '死亡守卫', '30K', '英雄'],
    hp: 24,
    maxHp: 24,
    ahp: 140,
    movement: 8,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '寂静(S:+50 D:25 能量 范围 横扫)'
  },
  'magnus_the_red_30k': {
    name: '马格努斯 (Magnus the Red) - 30K',
    status: '千子原体 / 独眼巨人',
    attributes: { weaponSkill: 85, ballisticSkill: 85, strength: 75, toughness: 80, agility: 75, intelligence: 100, perception: 100, willpower: 100, fellowship: 80 },
    trait: '【原体】：全属性受超凡加成；【灵能巅峰】：能施放所有学派灵能，获得 +30 加成；【第二视野】：感知(Per)可透视物质；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '灵能掌控, 博学, 逻辑, 武器技能, 警觉',
    equipment: '普罗斯佩罗法杖, 阿蒙之铠',
    tags: ['帝国', '阿斯塔特', '原体', '千子', '30K', '英雄'],
    hp: 16,
    maxHp: 16,
    ahp: 120,
    movement: 8,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '灵能法杖(S:PR×5,+15 D:10+PR)'
  },
  'horus_lupercal_30k': {
    name: '荷鲁斯·卢佩卡尔 (Horus Lupercal) - 30K',
    status: '影月苍狼原体 / 帝国战帅',
    attributes: { weaponSkill: 100, ballisticSkill: 95, strength: 80, toughness: 80, agility: 80, intelligence: 95, perception: 95, willpower: 100, fellowship: 100 },
    trait: '【原体】：全属性受超凡加成；【战帅威仪】：全场友军WS/BS+10；【战略天才】：指挥对抗绝对优先；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '指挥, 战略, 武器技能, 社交, 警觉',
    equipment: '荷鲁斯之爪, 碎船者',
    tags: ['帝国', '阿斯塔特', '原体', '影月苍狼', '30K', '英雄'],
    hp: 16,
    maxHp: 16,
    ahp: 130,
    movement: 9,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '碎船者(S:+55 D:28 冲击 眩晕), 荷鲁斯之爪(S:+45 D:22 能量 撕裂)'
  },
  'lorgar_aurelian_30k': {
    name: '洛嘉·奥瑞利安 (Lorgar Aurelian) - 30K',
    status: '怀言者原体 / 圣言者',
    attributes: { weaponSkill: 85, ballisticSkill: 85, strength: 70, toughness: 75, agility: 75, intelligence: 95, perception: 95, willpower: 100, fellowship: 100 },
    trait: '【原体】：全属性受超凡加成；【演说大师】：社交对抗获得 +30 加成；【灵能启迪】：协助友军提升意志(WP)对抗；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '神学, 演说, 社交, 武器技能, 指挥',
    equipment: '圣光, 金色盔甲',
    tags: ['帝国', '阿斯塔特', '原体', '怀言者', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 8,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '圣光(S:+45 D:22 能量 冲击)'
  },
  'vulkan_30k': {
    name: '伏尔甘 (Vulkan) - 30K',
    status: '火蜥蜴原体 / 普罗米修斯',
    attributes: { weaponSkill: 95, ballisticSkill: 85, strength: 100, toughness: 100, agility: 60, intelligence: 90, perception: 90, willpower: 100, fellowship: 90 },
    trait: '【原体】：全属性受超凡加成；【永久者】：死亡后将在一定时间后重生（系统核心设定）；【锻造之王】：可现场制造高精度零件；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '锻造, 武器技能, 强健, 领导, 警觉',
    equipment: '黎明之光, 德拉克鳞铠',
    tags: ['帝国', '阿斯塔特', '原体', '火蜥蜴', '30K', '英雄'],
    hp: 25,
    maxHp: 25,
    ahp: 160,
    movement: 7,
    baseMeleeDamage: '5 (S/20)',
    weaponStats: '黎明之光(S:+60 D:30 冲击 破甲)'
  },
  'corvus_corax_30k': {
    name: '科武斯·科拉克斯 (Corvus Corax) - 30K',
    status: '暗鸦守卫原体 / 解放者',
    attributes: { weaponSkill: 95, ballisticSkill: 95, strength: 75, toughness: 75, agility: 100, intelligence: 95, perception: 100, willpower: 95, fellowship: 75 },
    trait: '【原体】：全属性受超凡加成；【隐形之术】：只要不被肉眼直接注视即可视为隐形；【暗箭伤人】：伏击伤害翻倍；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '潜行, 武器技能, 追踪, 逻辑, 警觉',
    equipment: '暗影爪, 鞭打者, 飞行背包',
    tags: ['帝国', '阿斯塔特', '原体', '暗鸦守卫', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 15,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '暗影爪(S:+45 D:22 能量 撕裂)'
  },
  'alpharius_omegon_30k': {
    name: '阿尔法瑞斯 (Alpharius/Omegon) - 30K',
    status: '阿尔法军团原体 / “我即阿尔法”',
    attributes: { weaponSkill: 95, ballisticSkill: 95, strength: 70, toughness: 70, agility: 90, intelligence: 100, perception: 100, willpower: 95, fellowship: 95 },
    trait: '【原体】：全属性受超凡加成；【多重身份】：可以完美伪装成军团中的任何战士，干扰敌人信息锁定；【渗透之王】：在计划部署阶段获得 +30 加成；【体型·普通】：与普通星际战士体型无异，无法被目视识别为原体',
    skill: '伪装, 渗透, 逻辑, 武器技能, 警觉',
    equipment: '苍白之矛, 毒蛇之铠',
    tags: ['帝国', '阿斯塔特', '原体', '阿尔法军团', '30K', '英雄'],
    hp: 14,
    maxHp: 14,
    ahp: 100,
    movement: 9,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '苍白之矛(S:+45 D:25 维度 锋利)'
  },
  'sanguinius_30k': {
    name: '圣吉列斯 (Sanguinius) - 30K',
    status: '圣血天使原体 / 圣洁者',
    attributes: { weaponSkill: 100, ballisticSkill: 90, strength: 75, toughness: 75, agility: 100, intelligence: 90, perception: 100, willpower: 100, fellowship: 100 },
    trait: '【原体】：全属性受超凡加成；【大天使之翼】：飞行高度不限，俯冲攻击获得+20WS加成；【预知】：格挡计算时敏捷(Ag)+20；【体型·大型】：被攻击时敏捷(Ag)-5',
    skill: '突击, 武器技能, 艺术, 警觉, 社交',
    equipment: '圣吉列斯之剑, 黄金盔甲',
    tags: ['帝国', '阿斯塔特', '原体', '圣血天使', '30K', '英雄'],
    hp: 15,
    maxHp: 15,
    ahp: 110,
    movement: 15,
    baseMeleeDamage: '3 (S/20)',
    weaponStats: '圣吉列斯之剑(S:+45 D:22 能量 锋利)'
  },
  'rogal_dorn_30k': {
    name: '罗格·多恩 (Rogal Dorn) - 30K',
    status: '帝国之拳原体 / 泰拉禁卫',
    attributes: { weaponSkill: 95, ballisticSkill: 95, strength: 80, toughness: 85, agility: 70, intelligence: 95, perception: 95, willpower: 100, fellowship: 80 },
    trait: '【原体】：全属性受超凡加成；【不屈堡垒】：阵地防御无视压制效果；【黄金盾墙】：保护身侧友军；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '防御, 建筑, 武器技能, 指挥, 管理',
    equipment: '风暴之牙, 黄金护甲',
    tags: ['帝国', '阿斯塔特', '原体', '帝国之拳', '30K', '英雄'],
    hp: 17,
    maxHp: 17,
    ahp: 130,
    movement: 8,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '风暴之牙(S:+50 D:25 撕裂 链锯)'
  },
  'leman_russ_30k': {
    name: '黎曼·鲁斯 (Leman Russ) - 30K',
    status: '太空野狼原体 / 王狼',
    attributes: { weaponSkill: 100, ballisticSkill: 85, strength: 85, toughness: 85, agility: 85, intelligence: 85, perception: 100, willpower: 95, fellowship: 75 },
    trait: '【原体】：全属性受超凡加成；【芬里斯咆哮】：释放气势强制敌人意志对抗；【猎杀之主】：对特定单体目标伤害增加；【体型·大型】：被攻击时敏捷(Ag)-5, 移动力+1',
    skill: '追踪, 突击, 武器技能, 强健, 警觉',
    equipment: '狄翁尼斯之矛, 寒冰之爪',
    tags: ['帝国', '阿斯塔特', '原体', '太空野狼', '30K', '英雄'],
    hp: 17,
    maxHp: 17,
    ahp: 120,
    movement: 9,
    baseMeleeDamage: '4 (S/20)',
    weaponStats: '狄翁尼斯之矛(S:+60 D:30 灵能对抗)'
  }
};

const outputDir = './lib/knowledge/bestiary/primarchs';
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(
  path.join(outputDir, 'data_30k.ts'),
  `export const primarchs30kData = ${JSON.stringify(primarchs30k, null, 2)};`
);

console.log(`Successfully generated ${Object.keys(primarchs30k).length} 30K primarchs at ${outputDir}/data_30k.ts`);
